[project]
name = "sl-sign-language"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.135.2",
    "keras>=3.13.2",
    "numpy>=2.4.3",
    "scikit-learn>=1.8.0",
    "tensorflow>=2.21.0",
    "uvicorn[standard]>=0.42.0",
    "websockets>=16.0",
]
